### Primero cargamos la libreria pandas aunque no la necesitaremos en un comienzo, si es necesaria para los pasos posteriores, continuando con la resolucion, abrimos el archivo en modo lectura usando "with open" y agregamos como encoding utf8 ya que sin esto la lectura del archivo no es correcta

### Continuando con la resolucion, creamos la variable "agente" y "planta", para que estas almacenen la informacion deseada, aunque en un comienzo estaran vacias, asi mismo crearemos una lista llamada data donde guardaremos cada una de las lineas procesadas.

### despues de crear las variables, realizamos un ciclo for para recorrer el archivo y cuando encuentre la palabra agente este la almacene en su variable correspondiente que es "agente", continuando el flujo si la linea tiene al menos una longitud de 2 se continuara procesando dividiendola por comas y eliminando los espacios en blanco por ultimo se guardara en la variable "planta"

### el flujo final establece la condicion de que cada linea procesada que cumpla que su indice 1 sea D se concatenara su agente, planta y sus horas, añadiendo este ultimo resultado a nuestra lista data.

In [13]:
import pandas as pd

In [3]:
data = [] 
with open("./Prueba_Tecnica/Datos3/OFEI1204.txt",encoding="utf8") as files:
    lines = files.readlines()
    agente = ''
    planta = ''
    for line in lines:
        if line.startswith('AGENTE:'):
            agente = line.strip().split(":")[1].strip()
        elif line.strip() and len(line.strip().split(',')) >= 2:
            parts = line.strip().split(',')
            planta = parts[0].strip()
            if parts[1].strip() == 'D':
                horas = [float(part.strip()) for part in parts[2:]]
                data.append([agente,planta] + horas)

### Guardamos los datos previamente manipulados en un dataframe y así mismo creamos las columnas correspondientes para agente, planta y a las 24 hrs

In [10]:
data = pd.DataFrame(data)
column_names = ["Agente","Planta"] + [f'Hora_{i}' for i in range(1,25)]
data.columns = column_names

### Revisamos que el dataframe generado, sea correcto

In [11]:
data

,Agente,Planta,Hora_1,Hora_2,Hora_3,Hora_4,Hora_5,Hora_6,Hora_7,Hora_8,...,Hora_15,Hora_16,Hora_17,Hora_18,Hora_19,Hora_20,Hora_21,Hora_22,Hora_23,Hora_24
0,AES CHIVOR,CHIVOR1,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,...,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00
1,AES CHIVOR,CHIVOR2,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,...,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00
2,AES CHIVOR,CHIVOR3,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,...,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00
3,AES CHIVOR,CHIVOR4,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,...,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00
4,AES CHIVOR,CHIVOR5,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,...,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00,125.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,VATIA S.A.,SANTIAGO,1.52,1.52,1.52,1.52,1.52,1.52,1.52,1.52,...,1.52,1.52,1.52,1.52,1.52,1.52,1.52,1.52,1.52,1.52
301,VATIA S.A.,INCAUCA1,8.50,8.50,8.50,8.50,8.50,8.50,8.50,8.50,...,8.50,8.50,8.50,8.50,8.50,8.50,8.50,8.50,8.50,8.50
302,VATIA S.A.,INGENIOPROVIDENCIA2,13.80,13.80,13.80,13.80,13.80,13.80,13.80,13.80,...,13.80,13.80,13.80,13.80,13.80,13.80,13.80,13.80,13.80,13.80
303,ZF CELSIA,FLORES1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
304,ZF CELSIA,FLORES4B,450.00,450.00,450.00,450.00,450.00,450.00,450.00,450.00,...,450.00,450.00,450.00,450.00,450.00,450.00,450.00,450.00,450.00,450.00

### Guardamos el archivo generado con la manipulacion de datos anteriormente

In [12]:
data.to_csv("./Prueba_Tecnica/Resultados/Ejercicio1.csv",index = False)